language: objective-c
env:
  global:
  - WORKSPACE=Example/NVActivityIndicatorViewExample.xcworkspace
  - SCHEME=NVActivityIndicatorViewTests
matrix:
  include:
  - osx_image: xcode9
    env: SDK="iphonesimulator11.0" DESTINATION="name=iPhone 6s,OS=11.0"
script:
  - set -o pipefail
  - pod install --project-directory=Example
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES clean test | xcpretty -c
